### ISSUE TITLE
build fails because of SDL2MAIN_LIBRARY

### ISSUE THREAD

**Issue by teamblubee** [milkytracker/MilkyTracker#168] opened 2018-11-13 19:48 UTC
SDL2MAIN_LIBRARY seems to be only required for windows, this causes link failures on other platforms.

Here's a quick fix
```diff
--- FindSDL2.cmake.orig	2018-11-13 14:46:59.525542275 -0500
+++FindSDL2.cmake	2018-11-13 14:44:32.233172023 -0500
@@ -93,7 +93,11 @@
 endif()
 
 set(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})
-set(SDL2_LIBRARIES ${SDL2MAIN_LIBRARY} ${SDL2_LIBRARY})
+if(WIN32)
+	set(SDL2_LIBRARIES ${SDL2MAIN_LIBRARY} ${SDL2_LIBRARY})
+else()
+	set(SDL2_LIBRARIES ${SDL2_LIBRARY})
+endif()
```
 
 include(FindPackageHandleStandardArgs)

**Comment by Deltafire** [comment] 2018-11-22 17:55
I haven't had the time to look into this yet, but I'm a bit curious since Windows shouldn't be using SDL at all!

**Comment by MBeijer** [comment] 2018-11-30 09:02
@Deltafire You can use SDL2 on Windows too, if you want to. Not that I see any reason why you'd want that though.

**Comment by teamblubee** [comment] 2018-12-07 15:12
> @Deltafire You can use SDL2 on Windows too, if you want to. Not that I see any reason why you'd want that though.

I am not using Windows.

I just checked out: 119b9d7e35fcea8d891608f54e38d9d55412e4ea

and the issue still remains.

you have cmake find_package(SDL2 2 REQUIRED)

but you never actually link against the libraries

I think your testing environment might be polluted. Try building in a virtual environment or a clean system then the errors might appear.

The build still fails this patch resolves the issue.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ca90f53..b1f666c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -163,6 +163,7 @@ else()
     cmake_policy(SET CMP0004 OLD)
 
     find_package(SDL2 2 REQUIRED)
+    set(SDL2_LIBRARIES ${SDL2_LIBRARY})
 endif()
 
 # Prefer static linkage under OS X for libraries located with find_package()
```

**Comment by Deltafire** [comment] 2019-06-28 19:28
Tested with no errors on Ubuntu 14.04.3 via Travis and also on Ubuntu 19.04.

**Comment by apurkrt** [comment] 2019-10-15 11:50
The build on gentoo 64bit fails too.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SDL2MAIN_LIBRARY

**Comment by apurkrt** [comment] 2019-10-15 12:11
`cmake .. -DSDL2MAIN_LIBRARY=/usr/lib64/libSDL2.so`
is required to successfully compile

**Comment by dwhinham** [comment] 2019-10-15 12:20
The CMake scripts could do with being modernized. I wrote them a few years ago and problems like this will go away if we update the package finding stuff to use current methods.

`FindSDL2.cmake` was a bit of a crutch and it should be possible to delete it entirely and rely on `sdl2-config.cmake`, which should be provided by your distribution's SDL2 developer package in a location that CMake searches.

Doing `set(SDL2_LIBRARIES ${SDL2_LIBRARY})` inside our CMakeLists is a hack; instead, the discovery mechanism should be fixed.

RE: SDL build on Windows - yeah, you might be able to do it if you know how to configure CMake to find it properly but we **don't support/encourage it**.

**Comment by dwhinham** [comment] 2019-10-15 12:27
Tested build on a clean Ubuntu 18.04 machine and it built fine.

@teamblubee Please provide details of your OS/distribution version; you didn't mention what you're building on.

Cheers :)

**Comment by dwhinham** [comment] 2019-10-15 12:39
@teamblubee and @apurkrt 

Please try deleting `cmake/FindSDL2.cmake`, and change line 169 of `CMakeLists.txt` from
`find_package(SDL2 2 REQUIRED)`
to
`find_package(SDL2 REQUIRED)`

Then delete your build folder, try to reconfigure again and report back.

**Comment by apurkrt** [comment] 2019-10-15 12:46
@dwhinham That is indeed a fix! I can create the makefiles with just `cmake ..` and build without any problems (on gentoo ~amd64).

**Comment by dwhinham** [comment] 2019-10-15 12:51
Great - thanks for that! In theory, this should work for any Linux distribution that ships SDL2 properly. If the OP confirms this works I'll commit a fix.

**Comment by apurkrt** [comment] 2019-10-20 15:49
Just tested on Fedora 30 64bit. Same problem occurs, and your fix works there too.

**Closed** 2019-10-31 21:25 UTC

**Comment by dwhinham** [comment] 2019-10-31 21:29
Assuming fixed based on feedback from you guys, so I've pushed a commit.

Thanks for the testing! :+1:

(I can't test on Mac with the `FORCESDL` option, but I'm hoping that by removing `FindSDL2.cmake` and re-enabling `CMAKE_FIND_FRAMEWORK` the Frameworks method of locating SDL2 should just work as long as the SDL2 framework is in the right place.)

**Comment by apurkrt** [comment] 2019-12-07 09:40
Hi, how about a new (minor) release, now that the issue is fixed?
