### ISSUE TITLE
i can't restore settings to how it is on default, even if i delete it and reinstall it.

### ISSUE THREAD

**Issue by HXAPEWiZZ** [milkytracker/MilkyTracker#175] opened 2019-03-10 16:06 UTC
extra info: i use winrar and firefox quantum on windows 10.

**Comment by HXAPEWiZZ** [comment] 2019-03-10 16:14
my problem is that i can't do much with 8x pixels on 1080p window with only a 1080p screen. so now it's like 8000+p window that gets cut to the upper left corner to 1080p. i guess this could be fixed if settings were in the left corner of the screen or if there were hotkeys for every operation possible on this program (e.g.: having a hotkey to toggle pixelsize that is: num+ctrl+leftshift+rightshift+esc+alt+tab+q+del).

**Comment by sagamusix** [comment] 2019-03-15 21:32
MilkyTracker stores its settings in `%APPDATA%\MilkyTracker`. You must delete this folder, not the folder containing the executable.

**Comment by Deltafire** [comment] 2019-06-28 20:51
Duplicate of #166.

**Closed by Deltafire** 2019-06-28 20:51 UTC
