### ISSUE TITLE
README / INSTALL not updated after configure.ac removed

### ISSUE THREAD

**Issue by krs013** [milkytracker/MilkyTracker#61] opened 2017-02-03 18:37 UTC
It looks like configure.ac was [removed](https://github.com/milkytracker/MilkyTracker/commit/44bc66488bb909033cd361173f05744cc60928fc#diff-67e997bcfdac55191033d57a16d1408a) but the installation instructions in the root README and INSTALL files still refer to autoreconf, so it's not clear what replaced them. (I'm still trying to build, actually)

**Comment by Deltafire** [comment] 2017-02-05 22:37
Duplicate of #52

**Closed by Deltafire** 2017-02-05 22:37 UTC
