### ISSUE TITLE
Transpose: Single instrument buttons are frozen

### ISSUE THREAD

**Issue by DeerTears** [milkytracker/MilkyTracker#186] opened 2019-08-22 17:57 UTC
**Action:** Pressing the + and - buttons to select a single instrument to transpose in the transpose menu
**Expected result:** The number starts at 00hx and moves up and down in hexadecimal
**Actual result:** The number starts above 30hx and only one button changes the selection number

**Recreation:**

Load an .xm made from a current Milkytracker version or a previous Milkytracker version. Go to transposition and try to change the single instrument selection. Only the + or the - button will work and the starting number will be absurdly high.

**More details around when it's caused:**

On launch my single instrument transposition number starts off at a number like 32hx or 42hx. If I start editing data in the empty file, the number jumps up to something else - A1 as an example - and it seems like only the previously pressed button works, although it could very well be random chance.

After loading an .xm file the single instrument transposition number will move as well. From my experiments in loading files (both files created with 1.02.00 and older) I ended up with 61, D2 and 81 as some of my selection numbers. Loading the same file gave me a consistent number, but loading consecutive files gave me a different number, as if an ongoing calculation is happening to the single instrument selection number whenever new notes are loaded/placed into Milkytracker.

If there's some kind of relevant configuration file or log that I can send, please let me know. Thanks.

EDIT: I'm using 1.02.00 64bit. My ASUS laptop is running Windows 10 Home v1809.

**Comment by dwhinham** [comment] 2020-01-22 15:48
Thanks for the detailed report - this was caused by the variable being uninitialized and taking on a random value. This random value could be out of range, meaning the +/- buttons misbehaved.

The fix will be in the next release, or you can get it now by downloading a build from our Windows CI system: https://ci.appveyor.com/project/Deltafire/milkytracker/builds/30287530/job/30ae8eth8dmbmxq4/artifacts

**Closed by dwhinham** 2020-01-22 15:48 UTC
